"""
Natural Abundance Isotope Pattern Generator (Task E)
Calculates isotopic envelopes for candidate ions:
- 13C abundance (1.10% per carbon atom, M+1)
- 37Cl abundance (~3:1 ratio for 35Cl:37Cl at M and M+2)
- 81Br abundance (~1:1 ratio for 79Br:81Br at M and M+2)
- 34S abundance (4.4% per sulfur atom, M+2)
- Combinatorial binomial expansion for multi-halogen systems
"""

from typing import Dict, List, Tuple
from dataclasses import dataclass
import math

from src.fragmentation import FragmentCandidate


@dataclass
class IsotopePeak:
    """Represents an individual isotopic mass peak."""
    nominal_mz: int
    intensity: float
    annotation: str
    parent_mz: int


class IsotopeEngine:
    """Generates natural isotopic envelopes for molecular and fragment ions."""

    def __init__(self):
        # Abundance constants
        self.c13_rate = 0.0110
        self.n15_rate = 0.0037
        self.h2_rate = 0.00015
        self.s34_rate = 0.0440
        self.o18_rate = 0.0020

        # Halogen isotope probabilities
        self.cl35_prob = 0.7577
        self.cl37_prob = 0.2423

        self.br79_prob = 0.5069
        self.br81_prob = 0.4931

    def generate_envelope(self, candidate: FragmentCandidate, base_intensity: float) -> List[IsotopePeak]:
        """
        Compute all isotopic peaks (M, M+1, M+2, M+4) generated by a candidate fragment ion.
        Returns a list of IsotopePeak objects.
        """
        if base_intensity <= 0:
            return []

        peaks: List[IsotopePeak] = []
        counts = candidate.atom_counts
        n_c = counts.get('C', 0)
        n_h = counts.get('H', 0)
        n_n = counts.get('N', 0)
        n_o = counts.get('O', 0)
        n_s = counts.get('S', 0)
        n_cl = counts.get('Cl', 0)
        n_br = counts.get('Br', 0)

        # 1. Halogen multiplet calculation
        # If no halogens, base peak is pure M
        if n_cl == 0 and n_br == 0:
            # Main monoisotopic peak
            peaks.append(IsotopePeak(
                nominal_mz=candidate.nominal_mz,
                intensity=base_intensity,
                annotation="monoisotopic",
                parent_mz=candidate.nominal_mz
            ))

            # M+1 envelope (13C, 15N, 2H)
            m_plus_1_frac = (n_c * self.c13_rate) + (n_n * self.n15_rate) + (n_h * self.h2_rate)
            if m_plus_1_frac > 0.001:
                peaks.append(IsotopePeak(
                    nominal_mz=candidate.nominal_mz + 1,
                    intensity=base_intensity * m_plus_1_frac,
                    annotation=f"M+1 ({n_c}×¹³C)",
                    parent_mz=candidate.nominal_mz
                ))

            # M+2 envelope (34S, 18O, second-order 13C)
            m_plus_2_frac = (n_s * self.s34_rate) + (n_o * self.o18_rate)
            if n_c >= 2:
                # Second-order 13C probability: (n_c choose 2) * (0.011)^2
                m_plus_2_frac += (n_c * (n_c - 1) / 2.0) * (self.c13_rate ** 2)

            if m_plus_2_frac > 0.001:
                peaks.append(IsotopePeak(
                    nominal_mz=candidate.nominal_mz + 2,
                    intensity=base_intensity * m_plus_2_frac,
                    annotation="M+2 (³⁴S/¹⁸O/¹³C₂)",
                    parent_mz=candidate.nominal_mz
                ))

        else:
            # Halogenated species: Compute binomial expansion for Cl and Br
            halogen_distribution = self._calculate_halogen_distribution(n_cl, n_br)

            # Find the most abundant halogen peak for normalization
            max_p = max(p for _, p in halogen_distribution)

            for delta_mz, prob in halogen_distribution:
                scaled_intensity = base_intensity * (prob / max_p)
                mz = candidate.nominal_mz + delta_mz

                label = "M" if delta_mz == 0 else f"M+{delta_mz}"
                if n_cl > 0 and n_br == 0:
                    label += f" ({n_cl}×Cl pattern)"
                elif n_br > 0 and n_cl == 0:
                    label += f" ({n_br}×Br pattern)"
                else:
                    label += f" ({n_cl}×Cl, {n_br}×Br)"

                peaks.append(IsotopePeak(
                    nominal_mz=mz,
                    intensity=scaled_intensity,
                    annotation=label,
                    parent_mz=candidate.nominal_mz
                ))

                # Also add 13C satellite for each halogen peak
                if n_c > 0:
                    c13_intensity = scaled_intensity * (n_c * self.c13_rate)
                    if c13_intensity > 0.005 * base_intensity:
                        peaks.append(IsotopePeak(
                            nominal_mz=mz + 1,
                            intensity=c13_intensity,
                            annotation=f"{label} + ¹³C",
                            parent_mz=candidate.nominal_mz
                        ))

        return peaks

    def _calculate_halogen_distribution(self, n_cl: int, n_br: int) -> List[Tuple[int, float]]:
        """
        Compute the discrete distribution of mass shifts and probabilities for n_cl and n_br atoms.
        35Cl: 0.7577 (delta=0), 37Cl: 0.2423 (delta=+2)
        79Br: 0.5069 (delta=0), 81Br: 0.4931 (delta=+2)
        """
        # Dictionary of delta_mz (0, 2, 4, ...) -> probability
        dist: Dict[int, float] = {0: 1.0}

        # Convolve Cl atoms
        for _ in range(n_cl):
            new_dist: Dict[int, float] = {}
            for d, p in dist.items():
                new_dist[d] = new_dist.get(d, 0.0) + p * self.cl35_prob
                new_dist[d + 2] = new_dist.get(d + 2, 0.0) + p * self.cl37_prob
            dist = new_dist

        # Convolve Br atoms
        for _ in range(n_br):
            new_dist: Dict[int, float] = {}
            for d, p in dist.items():
                new_dist[d] = new_dist.get(d, 0.0) + p * self.br79_prob
                new_dist[d + 2] = new_dist.get(d + 2, 0.0) + p * self.br81_prob
            dist = new_dist

        return sorted(dist.items(), key=lambda x: x[0])
